#!/bin/bash -e

export LD_LIBRARY_PATH="$SNAP_DATA/opt/workspacesclient/:$SNAP_DATA/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pcoip-client/vchan_plugins${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

exec $SNAP_DATA/opt/workspacesclient/workspacesclient